/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package pl.polsl.viewpackage;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 * A view for displaying reports.
 * @author Piotr
 * @version 2.0
 */
public class ShowDatabase extends javax.swing.JFrame{
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane scrollDatabase;
    private javax.swing.JTable databaseTable;
    // End of variables declaration
   /**
     * Creates new form Show_Report
     */
    public ShowDatabase() {
        initComponents();
        cancelButton.setToolTipText("Quit the window \n Shortcut: ALT+G");
        cancelButton.setMnemonic('G');
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * regenerated by the Form Editor.
     */
    private void initComponents(){
        cancelButton = new javax.swing.JButton();
        scrollDatabase = new javax.swing.JScrollPane();
        databaseTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        databaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null}
            },
            new String [] {
                "Author", "Title", "Region", "Listeners","Song_Time"
            }
        ));
        scrollDatabase.setViewportView(databaseTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(scrollDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addContainerGap())
        );

        pack();
    }
    /**
    * Handles the action when the "Close" button is clicked.
    *
    * @param evt The ActionEvent object representing the event.
    */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        //jTextArea1.setText("");
        dispose();
    }                                        
    /**
    * Displays the contents of a text file in a JTable.
    *
    * @param filePath The path to the text file to be displayed.
    */
    public void displayDatabaseContents(String filePath) {
        // Assuming databaseTable is the name of your JTable
        DefaultTableModel model = (DefaultTableModel) databaseTable.getModel();

        // Clear the existing rows in the table
        model.setRowCount(0);

        String line;
        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            while ((line = reader.readLine()) != null) {
                String[] fields = line.split(" "); 

                model.addRow(fields);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
 
}
